TGF.WebApp/Controllers/StoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using TGF.WebApp.Models;

namespace TGF.WebApp.Controllers
{
    public class StoryController : Controller
    {
        public IConfiguration Configuration;
        private JWToken JWToken;

        public StoryController(IConfiguration configuration, JWToken jWToken)
        {
            Configuration = configuration;
            JWToken = jWToken;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            return ControllerContext.RouteData.Values["controller"].ToString();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var tokenString = JWToken.GenerateJSONWebToken();

            //string _restpath = "https://localhost:5001/profile";
            string _restpath = GetHostUrl().Content + CN();

            List<StoryVM> storiesList = new List<StoryVM>();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    storiesList = JsonConvert.DeserializeObject<List<StoryVM>>(apiResponse);
                }
            }

            return View(storiesList);
        }

        [Authorize]
        public async Task<IActionResult> Get(int id, int character)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();
            StoryVM s = new StoryVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        s = JsonConvert.DeserializeObject<StoryVM>(apiResponse);
                    }

                    if (s == null)
                    {
                        TempData["Message"] = "Brak Historii!";
                        TempData["Category"] = "danger";
                        if (User.IsInRole("Admin"))
                        {
                            return RedirectToAction("Index");
                        }
                        return RedirectToAction("Get", "Character", new { id = character });
                    }

                    using (var response = await httpClient.GetAsync($"{GetHostUrl().Content}character"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        s.OtherCharacters = JsonConvert.DeserializeObject<List<CharacterVM>>(apiResponse);
                        foreach(CharacterVM c in s.Characters)
                        {
                            s.OtherCharacters.Remove(s.OtherCharacters.First(x => x.Id == c.Id)); 
                        }
                    }
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            return View(s);
        }

        [Authorize]
        public IActionResult Create(int character)
        {
            StoryVM characterVM = new StoryVM() { FromCharacter = character };

            return View(characterVM);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(StoryVM s)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();
            int Id = 0;

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

                    var response = await httpClient.PostAsync(_restpath, content);
                    if (!response.IsSuccessStatusCode)
                    {
                        TempData["Message"] = "Błąd tworzenia story!";
                        TempData["Category"] = "danger";
                        if (User.IsInRole("Admin"))
                        {
                            return RedirectToAction("Index");
                        }
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        Id = int.Parse(response.Headers.Location.Segments[2]);
                    }
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction("Create", "CharacterStory", new { sId = Id, cId = s.FromCharacter});
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            StoryVM s = new StoryVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        s = JsonConvert.DeserializeObject<StoryVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            if (s == null)
            {
                TempData["Message"] = "Nie można pobrać historii!";
                TempData["Category"] = "danger";
                return RedirectToAction("Index");
            }

            return View(s);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(StoryVM s)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            StoryVM sResult = new StoryVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

                    using (var response = await httpClient.PutAsync($"{ _restpath}/{s.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        sResult = JsonConvert.DeserializeObject<StoryVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            StoryVM s = new StoryVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.GetAsync($"{ _restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        s = JsonConvert.DeserializeObject<StoryVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            if (s == null)
            {
                TempData["Message"] = "Nie można pobrać historii!";
                TempData["Category"] = "danger";
                return RedirectToAction("Index");
            }

            return View(s);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(StoryVM p)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using var response = await httpClient.DeleteAsync($"{ _restpath}/{p.Id}");
                }

TGF.WebApp/Views/Post/Create.cshtml
@model TGF.WebApp.Models.PostVM

<h4>Create new post</h4>
<hr />
<div class="row">
    <div class="col">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (!User.IsInRole("Admin"))
            {
                <div class="form-group">
                    <label class="control-label">Wybierz postać</label>
                    <select asp-for="CharacterId" class="custom-select" id="choosenCharacter">
                        @foreach (CharacterVM ch in Model.Profile.Characters.Where(c => c.Stories.Where(s => s.Id == Model.StoryId).Count() > 0))
                        {
                            <option value="@ch.Id">@ch.Name</option>
                        }
                    </select>
                    <span asp-validation-for="CharacterId" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control" rows="10"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <input asp-for="ProfileId" class="form-control" hidden />
            <input asp-for="StoryId" class="form-control" hidden />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@{
    if (User.IsInRole("Admin"))
    {
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    }
    else if (User.Identity.IsAuthenticated)
    {
        <div>
            <a class="" asp-controller="Story" asp-action="Get" asp-route-id="@Model.StoryId">Powrót do historii</a>
        </div>
    }
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TGF.WebApp/Views/Post/Delete.cshtml
@model TGF.WebApp.Models.PostVM

<h3>Are you sure you want to delete this post?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Tytuł
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            Data publikacji
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.PublicationDate)
        </dd>
        <dt class="col-sm-2">
            Autor
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Profile.Name)
        </dd>
        <dt class="col-sm-2">
            Kontent
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input asp-for="StoryId" class="form-control" hidden />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @{
            if (User.IsInRole("Admin"))
            {
                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            }
            else if (User.Identity.IsAuthenticated)
            {
                <div>
                    <a class="" asp-controller="Story" asp-action="Get" asp-route-id="@Model.StoryId">Powrót do historii</a>
                </div>
            }
        }
    </form>
</div>

TGF.WebApp/Views/Post/Edit.cshtml
@model TGF.WebApp.Models.PostVM

<h4>Edit post</h4>
<hr />
<div class="row">
    <div class="col">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control" rows="10"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <input asp-for="ProfileId" class="form-control" hidden />
            <input asp-for="CharacterId" class="form-control" hidden />
            <input asp-for="StoryId" class="form-control" hidden />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@{
    if (User.IsInRole("Admin"))
    {
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    }
    else if (User.Identity.IsAuthenticated)
    {
        <div>
            <a class="" asp-controller="Story" asp-action="Get" asp-route-id="@Model.StoryId">Powrót do historii</a>
        </div>
    }
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TGF.WebApp/Views/Post/Index.cshtml
@model IEnumerable<TGF.WebApp.Models.PostVM>

<h5 class="mb-3">Lista postów</h5>
<p>
    <a asp-action="Create">Create New</a>
</p>

@foreach (var post in Model)
{
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title post-title" data-toggle="collapse" data-target="#content-@post.Id">
               @post.Title
            </h5>
            <p class="card-text data">
                <small class="text-muted">@post.PublicationDate</small>
            </p>
            <p class="card-text collapse content text-justify" id="content-@post.Id">@post.Content</p>

            @*<p class="card-text collapse" id="content-hide-@item.Id">
                    @Html.DisplayFor(modelItem => item.Short)...
                    <a href="#" data-toggle="collapse" data-target="#content-show-@item.Id" onclick="toggle(@item.Id)"> Show more</a>
                </p>
                <p class="card-text collapse" id="content-show-@item.Id" hidden>
                    @Html.DisplayFor(modelItem => item.Content)
                    <a href="#" data-toggle="collapse" data-target="#content-hide-@item.Id" onclick="toggle(@item.Id)"> Hide</a>
                </p>*@
        </div>
        <div class="card-footer d-flex justify-content-between align-items-center">
            <p class="text-muted" style="margin: 0;">Autor: @post.Profile.Name</p>
            <div>
                <a class="card-link" asp-action="Edit" asp-route-id="@post.Id">Edytuj</a>
                <a class="card-link" asp-action="Delete" asp-route-id="@post.Id">Usuń</a>
            </div>
        </div>
    </div>
}

<style>
    .post-title:hover {
        cursor: pointer;
        color: #6c6767;
    }

    .foot {
        padding-top: 0;
    }

    .data {
        margin-bottom: 0;
    }

    .content {
        margin-top: 16px;
    }
</style>

<script>
    console.log(contentHide.hidden)

    function toggle(id) {
        var contentHide = document.getElementById('content-hide-' + id)
        var contentShow = document.getElementById('content-show-' + id)
        console.log(contentHide.hidden)
        console.log(contentShow.hidden)
        if (!contentHide.hidden) {
            contentHide.hidden = true;
            contentShow.hidden = false;
        } else {
            contentHide.hidden = false;
            contentShow.hidden = true;
        }
    }
</script>