TGF.WebApp/Controllers/CharacterStoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using TGF.WebApp.Models;

namespace TGF.WebApp.Controllers
{
    public class CharacterStoryController : Controller
    {
        public IConfiguration Configuration;
        private JWToken JWToken;

        public CharacterStoryController(IConfiguration configuration, JWToken jWToken)
        {
            Configuration = configuration;
            JWToken = jWToken;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            return ControllerContext.RouteData.Values["controller"].ToString();
        }

        //[Authorize]
        //public async Task<IActionResult> Get(int cId, int sId)
        //{
        //    //var tokenString = GenerateJSONWebToken();
        //    string _restpath = GetHostUrl().Content + CN();
        //    CharacterStoryVM cs = new CharacterStoryVM();

        //    try
        //    {
        //        using (var httpClient = new HttpClient())
        //        {
        //            //httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
        //            using (var response = await httpClient.GetAsync($"{_restpath}?cId={cId}&sId={sId}"))
        //            {
        //                string apiResponse = await response.Content.ReadAsStringAsync();
        //                cs = JsonConvert.DeserializeObject<CharacterStoryVM>(apiResponse);
        //            }
        //        }
        //    }
        //    catch (Exception e)
        //    {
        //       // return View(e);
        //    }

        //    //if (cs == null)
        //    //{
        //    //    TempData["Message"] = "Brak Historii!";
        //    //    TempData["Category"] = "danger";
        //    //    return RedirectToAction("Get", "Character", new { id = character });
        //    //}

        //    //return View(cs);
        //}

        [Authorize]
        public async Task<IActionResult> Create(int sId, int cId)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            CharacterStoryVM cs = new CharacterStoryVM()
            {
                CharactersId = cId,
                StoriesId = sId
            };

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(cs);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

                    using var response = await httpClient.PostAsync(_restpath, content);
                }
            }
            catch (Exception)
            {
                TempData["Message"] = "Błąd dodawania postaci do historii!";
                TempData["Category"] = "danger";
                return RedirectToAction("Get", "Story", new { id = sId });
            }

            return RedirectToAction("Get", "Story", new { id = sId });
        }

        //[Authorize(Roles = "Admin")]
        [Authorize]
        public async Task<IActionResult> Delete(int sId, int cId)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using var response = await httpClient.DeleteAsync($"{_restpath}?cId={cId}&sId={sId}");
                }
            }
            catch (Exception)
            {
                TempData["Message"] = "Błąd usuwania postaci z historii!";
                TempData["Category"] = "danger";
                return RedirectToAction("Get", "Story", new { id = sId });
            }

            return RedirectToAction("Get", "Story", new { id = sId });
        }
    }
}

TGF.WebApp/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using TGF.WebApp.Models;

namespace TGF.WebApp.Controllers
{
    public class PostController : Controller
    {
        public IConfiguration Configuration;
        private JWToken JWToken;
        private readonly ILogger<PostController> _logger;

        public PostController(IConfiguration configuration, JWToken jWToken, ILogger<PostController> logger)
        {
            Configuration = configuration;
            JWToken = jWToken;
            _logger = logger;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            return ControllerContext.RouteData.Values["controller"].ToString();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var tokenString = JWToken.GenerateJSONWebToken();

            //string _restpath = "https://localhost:5001/post";
            string _restpath = GetHostUrl().Content + CN();

            List<PostVM> postsList = new List<PostVM>();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    _logger.LogError("aaa");
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    postsList = JsonConvert.DeserializeObject<List<PostVM>>(apiResponse);
                }
            }

            foreach(var post in postsList)
            {
                if(post.Content != null)
                {
                    post.Short = post.Content.Substring(0, post.Content.Length < 200 ? post.Content.Length : 200);
                }
            }

            return View(postsList);
        }

        [Authorize]
        public async Task<IActionResult> Create(int story)
        {
            var tokenString = JWToken.GenerateJSONWebToken();

            PostVM post = new PostVM()
            {
                StoryId = story
            };

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.GetAsync($"{GetHostUrl().Content}profile/filter?username={User.Identity.Name}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        ProfileVM pr = JsonConvert.DeserializeObject<ProfileVM>(apiResponse);
                        if (pr != null)
                        {
                            post.ProfileId = pr.Id;
                            post.Profile = pr;
                        }
                        else
                        {
                            TempData["Message"] = "Nie udało się pobrać profilu użytkownika!";
                            TempData["Category"] = "danger";
                            if (User.IsInRole("Admin"))
                            {
                                return RedirectToAction("Index");
                            }
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            return View(post);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(PostVM p)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(p);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

                    var response = await httpClient.PostAsync(_restpath, content);
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction("Get", "Story", new { id = p.StoryId });
            }
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            PostVM p = new PostVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        p = JsonConvert.DeserializeObject<PostVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            if (p == null)
            {
                TempData["Message"] = "Nie można pobrać postu!";
                TempData["Category"] = "danger";
                if (User.IsInRole("Admin"))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("GetOne", "Profile", new { username = User.Identity.Name });
                }
            }

            return View(p);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(PostVM p)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            PostVM pResult = new PostVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(p);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

                    using (var response = await httpClient.PutAsync($"{ _restpath}/{p.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        pResult = JsonConvert.DeserializeObject<PostVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction("Get", "Story", new { id = pResult.StoryId });
            }
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            PostVM p = new PostVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.GetAsync($"{ _restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        p = JsonConvert.DeserializeObject<PostVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                return View(e);
            }

            if (p == null)
            {
                TempData["Message"] = "Nie można pobrać postu!";
                TempData["Category"] = "danger";
                if (User.IsInRole("Admin"))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("GetOne", "Profile", new { username = User.Identity.Name });
                }
            }

            return View(p);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Delete(PostVM p)
        {
            var tokenString = JWToken.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using var response = await httpClient.DeleteAsync($"{ _restpath}/{p.Id}");
                }
            }
            catch (Exception e)
            {
                return View(e);

TGF.WebApp/Views/Story/Create.cshtml
@model TGF.WebApp.Models.StoryVM

<h4>StoryVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <input asp-for="CreationDate" class="form-control" hidden />
            <input asp-for="FromCharacter" class="form-control" hidden />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@{
    if (User.IsInRole("Admin"))
    {
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    }
    else if (User.Identity.IsAuthenticated)
    {
        <div>
            <a class="" asp-controller="Character" asp-action="Get" asp-route-id="@Model.FromCharacter">Back to card</a>
        </div>
    }
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TGF.WebApp/Views/Story/Delete.cshtml
@model TGF.WebApp.Models.StoryVM

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StoryVM</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TGF.WebApp/Views/Story/Edit.cshtml
@model TGF.WebApp.Models.StoryVM

<h4>StoryVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <input asp-for="CreationDate" class="form-control" hidden />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TGF.WebApp/Views/Story/Get.cshtml
@model TGF.WebApp.Models.StoryVM
@using System.Security.Claims

<h5 class="mb-3">Historia</h5>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">@Model.Title</h4>
        <p class="card-text text-muted">Data utworzenia: @Model.CreationDate.ToShortDateString()</p>

        <h5 class="mb-3" style="font-size: 18px;">Uczestniczące postaci</h5>
        <ul class="list-group mb-4">
            @foreach (var ch in Model.Characters)
            {
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a class="text-dark card-link" asp-controller="Character" asp-action="Get" asp-route-id="@ch.Id">
                        @ch.Name
                        <span class="text-muted"> [@ch.Profile.Name]</span>
                    </a>
                    @if (ch.Profile.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value || User.IsInRole("Admin"))
                    {
                        <a class="text-dark card-link" asp-controller="CharacterStory" asp-action="Delete" asp-route-cId="@ch.Id" asp-route-sId="@Model.Id">Usuń postać</a>
                    }
                </li>
            }
        </ul>

        <div class="dropdown mb-4">
            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dodaj nową postać
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                @foreach (var ch in Model.OtherCharacters)
                {
                    <a class="dropdown-item" asp-controller="CharacterStory" asp-action="Create" asp-route-cId="@ch.Id" asp-route-sId="@Model.Id">
                        @ch.Name
                        <span class="text-muted"> [@ch.Profile.Name]</span>
                    </a>
                }
            </div>
        </div>

        <h5 class="mb-3" style="font-size: 18px;">Posty</h5>
        @if (!User.IsInRole("Admin"))
        {
            <p>
                <a class="card-link" asp-controller="Post" asp-action="Create" asp-route-story="@Model.Id">Dodaj nowy post</a>
            </p>
        }

        @foreach (var post in Model.Posts)
        {
            <div class="card mb-3">
                <div class="card-body">
                    <h6 class="card-title post-title" data-toggle="collapse" data-target="#content-@post.Id" style="font-size: 18px;">
                        @post.Character.Name: @post.Title
                    </h6>
                    <p class="card-text data">
                        <small class="text-muted">@post.PublicationDate</small>
                    </p>
                    <p class="card-text collapse content text-justify" id="content-@post.Id">@post.Content</p>
                </div>
                <div class="card-footer d-flex justify-content-between align-items-center">
                    <p class="text-muted" style="margin: 0;">Autor: @post.Character.Profile.Name</p>
                    <div>
                        @if (post.Character.Profile.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value)
                        {
                            <a class="card-link" asp-controller="Post" asp-action="Edit" asp-route-id="@post.Id">Edytuj</a>
                            <a class="card-link" asp-controller="Post" asp-action="Delete" asp-route-id="@post.Id">Usuń</a>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<style>
    .post-title:hover {
        cursor: pointer;
        color: #6c6767;
    }

    .foot {
        padding-top: 0;
    }

    .data {
        margin-bottom: 0;
    }

    .content {
        margin-top: 16px;
    }
</style>

TGF.WebApp/Views/Story/Index.cshtml
@model IEnumerable<TGF.WebApp.Models.StoryVM>

<h5 class="mb-3">Lista historii</h5>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.ActionLink("View", "Get", new { id = item.Id }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })

            </td>
        </tr>
}
    </tbody>
</table>